spring.application.name=user-registration
spring.port=8080


# Validates the schema and creates tables if they are missing
spring.jpa.hibernate.ddl-auto=update  # Use 'update' for development, 'validate' for production
spring.datasource.url=jdbc:mysql://localhost:3306/user_registration_db
spring.datasource.username=root
spring.datasource.password={yourpassword}